name: StCloneMaster src

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Accept Licenses
        run: yes | sdkmanager --licenses || true
      - name: Build
        run: ./gradlew assembleRelease
